--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JackMD/ScoreHud
branches:
- master
projects:
  ScoreHud:
    libs:
      - src: JackMD/ScoreFactory/ScoreFactory
        version: ^1.0.0
...