--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Ifera/ScoreHud
branches:
  - master
  - PM4
projects:
  ScoreHud:
    icon: meta/ScoreHud.PNG
    libs:
      - src: Ifera/ScoreFactory/ScoreFactory
        version: ^3.1.0
        branch: master
      - src: ifera-mc/UpdateNotifier/UpdateNotifier
        version: ^3.0.0
        branch: master
      - src: ifera-mc/ConfigUpdater/ConfigUpdater
        version: ^2.0.0
        branch: master
    lint:
      phpstan: false
...
