--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ACM-PocketMine-MP/ScoreHud
build-by-default: true
branches:
- PM5
projects:
  ScoreHud:
    path: ""
    icon: meta/ScoreHud.PNG
    libs:
      - src: ACM-PocketMine-MP/ScoreFactory/ScoreFactory
        version: ^4.0.0
        branch: PM5
      - src: ACM-PocketMine-MP/UpdateNotifier/UpdateNotifier
        version: ^4.0.0
        branch: PM5
      - src: ACM-PocketMine-MP/ConfigUpdater/ConfigUpdater
        version: ^3.0.0
        branch: PM5
    lint:
      phpstan: false
...
